version: '3.4'

services:
  inventory.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__IdentityDbConnection=User ID=postgres;Password=postgres;Server=postgres;Port=5432;Database=cIdentityDb;Pooling=true
      - AutoMigrate=True
      - JwtSettings__SecretKey=b97f>MNK%QZmFf8q5tR6GcA)8kuC.X;FMkqr5(HAmbky.aRR$V3
      - JwtSettings__RefreshSecret=w(N.3*r;(AUKZvS9BwBS$FGR-B>7T$ff<yz2SN Ve3RMjR%
      - JwtSettings__Issuer=CatalogIdentityMS
      - JwtSettings__ExpireTime=60
      - JwtSettings__RefreshTokenExpirationMin=120
      - JwtSettings__Audience=CatalogIdentityUser
      
    ports:
      - "80"

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ProductDbConnection=User ID=postgres;Password=postgres;Server=postgres;Port=5432;Database=cproductDb;Pooling=true
      - AutoMigrate=True
    ports:
      - "80"

  postgres:
      container_name: postgres
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres 
      restart: always
      ports:
         - "5433:5432" 
      volumes:
         - postgres-data:/var/lib/postgresql/data
      healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"



