version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine

  distributedcache:
    image: redis

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventory
    build:
      context: .
      dockerfile: src/Services/Inventory/Inventory.Api/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.Api/Dockerfile

  product.api:
    image: ${DOCKER_REGISTRY-}product
    build:
      context: .
      dockerfile: src/Services/Product/Product.Api/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile

volumes:
  postgres-data: